DROP TRIGGER checkcont;
DROP PROCEDURE calcula_orcamento;

TRUNCATE TABLE Especialidade_Professor;
DROP TABLE Especialidade_Professor CASCADE CONSTRAINTS;

TRUNCATE TABLE Contato_Estudante;
DROP TABLE Contato_Estudante CASCADE CONSTRAINTS;

TRUNCATE TABLE P_Trabalha;
DROP TABLE P_Trabalha CASCADE CONSTRAINTS;

TRUNCATE TABLE Trabalha;
DROP TABLE Trabalha CASCADE CONSTRAINTS;

TRUNCATE TABLE E_Trabalha;
DROP TABLE E_Trabalha CASCADE CONSTRAINTS;

TRUNCATE TABLE Projeto;
DROP TABLE Projeto CASCADE CONSTRAINTS;

TRUNCATE TABLE Estudante;
DROP TABLE Estudante CASCADE CONSTRAINTS;

TRUNCATE TABLE Departamento;
DROP TABLE Departamento CASCADE CONSTRAINTS;

TRUNCATE TABLE Professor;
DROP TABLE Professor CASCADE CONSTRAINTS;
